from schemas.base import TableSchema

SCHEMA = TableSchema(
    table="estabelecimentos",
    columns=[
        "cnpj_basico",
        "cnpj_ordem",
        "cnpj_dv",
        "matriz_filial",
        "nome_fantasia",
        "situacao_cadastral",
        "data_situacao",
        "motivo_situacao",
        "cidade_exterior",
        "pais",
        "data_inicio",
        "cnae_principal",
        "cnae_secundarios",
        "tipo_logradouro",
        "logradouro",
        "numero",
        "complemento",
        "bairro",
        "cep",
        "uf",
        "municipio",
        "ddd1",
        "telefone1",
        "ddd2",
        "telefone2",
        "ddd_fax",
        "fax",
        "email",
        "situacao_especial",
        "data_situacao_esp",
    ],
    pk_columns=["cnpj_basico", "cnpj_ordem", "cnpj_dv"],
    conflict_columns=["cnpj_basico", "cnpj_ordem", "cnpj_dv"],
)
