services:
  postgres:
    ports: !reset []
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d

  redis:
    ports: !reset []

  api:
    build: false
    image: cnpj-discovery-api:latest
    restart: always
    ports:
      - "8000:8000"

  enrichment:
    build: false
    image: cnpj-discovery-enrichment:latest
    restart: always
    ports: !reset []

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  pgdata:
    driver: local
